[project]
name = "edu-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = []

[tool.uv.workspace]
members = [
    "src/edu-api",
    "src/edu-worker",
    "src/edu-shared",
]
